# This workflow will build a docker container, publish it to IBM Container Registry, and deploy it to an existing IBM Kubernetes service cluster.
name: Build and Deploy to IKS

on:
  push: # Execute on every push to the master branch. Merging a pull request counts as a push.
    branches:
      - main

jobs:
  build-push-deploy-job:
    runs-on: ubuntu-latest
    name: A job to download and log into ibmcloud cli
    steps:
      - uses: actions/checkout@v2

      - name: Set general enviroment variables
        env:
          AGROLLY_BACKEND_CLOUD_URL: ${{ secrets.AGROLLY_BACKEND_CLOUD_URL }}
        run: |
          touch .env
          echo REACT_APP_BACKEND_URL=$AGROLLY_BACKEND_CLOUD_URL >> .env

      # Turnstyle ensures that this job only runs one at a time in this repository
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: call-for-code/build-push-deploy@v1
        with:
          cloud-api-key: ${{ secrets.IBM_CLOUD_API_KEY }}
          cloud-resource-group: Agrolly
          cloud-region: us-south
          deployment-name: agrolly-web
          github-sha: ${{ github.sha }}
          icr-namespace: ${{ secrets.ICR_NAMESPACE }}
          image-name: agrolly-web
          k8s-cluster-name: ${{ secrets.K8S_CLUSTER_NAME }}
          k8s-cluster-namespace: ${{ secrets.K8S_CLUSTER_NAMESPACE }}
          registry-hostname: us.icr.io
          working-directory: "."
